# @package _global_
defaults:
  - oc_base
  - /prior: gauss_truncate
  - /sde: vp_10
  - /model@generative_ctrl: potential
  - /loss: time_reversal_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.SubtrajBridge

# Subtraj
subtraj_prob: 0.5
fix_terminal: True
subtraj_steps:
lerp_domain: True

# Loss
loss:
  max_log_rnd: 1e4

# Model
generative_ctrl:
  clip_model: 10.

# EMA, optimizer, scheduler
optim:
  lr: 0.001
