# @package _global_
defaults:
  - oc_base
  - /prior: delta
  - /sde: bm_pis
  - /model@generative_ctrl: clipped
  - /loss: reference_sde_lv
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.PIS

# Model
generative_ctrl:
  clip_model: 10.
